github_url: https://github.com/StevenLambion/SwiftDux
documentation:
  - Guides/*.md
custom_categories:
  - name: "Documentation"
    children:
      - "Installation"
      - "Getting Started"
      - "Composing Reducers"
      - "SwiftUI List Support"
  - name: State
    children:
      - StateType
      - IdentifiableState
      - OrderedState
  - name: Actions
    children:
      - Action
      - EmptyAction
      - ActionPlan
      - PublishableActionPlan
      - ActionDispatcher
      - SendAction
      - GetState
      - ActionModifier
      - ModifiedAction
  - name: Store
    children:
      - Store
      - Reducer
      - StoreActionDispatcher
  - name: SwiftUI
    children:
      - View
      - MappedState
      - MappedDispatch
      - Connectable
      - ParameterizedConnectable
