on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=13.0,name=iPhone Xs"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Switch to workspace directory
        run: cd $GITHUB_WORKSPACE
      - name: Install tooling
        run: |
          sudo xcode-select -s /Applications/Xcode_11.app
          brew install mint
          mint install apple/swift-format
      - name: Lint
        run: |
          swift-format -r -m lint Sources
      - name: Test
        run: |
          swift package generate-xcodeproj
          xcodebuild clean test -project SwiftDux.xcodeproj -scheme SwiftDux-Package -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env:
          destination: ${{ matrix.destination }}
